import pygame

gramado = pygame.image.load('IMAGENS\Cemiterio2.png')
Som_game_over = pygame.mixer.Sound('SONS\Som_Game_Over.mp3')
Som_Tema = pygame.mixer.Sound('SONS\Som_Tema.mp3')
Som_Tema.set_volume(0.02)

Manoel_f = pygame.image.load('IMAGENS\Manoel_frente.png')
Manoel_c = pygame.image.load('IMAGENS\Manoel_costa.png')
Manoel_le = pygame.image.load('IMAGENS\Manoel_ladoE.png')
Manoel_ld = pygame.image.load('IMAGENS\Manoel_ladoD.png')
Manoel_frente = pygame.transform.scale(Manoel_f, (128, 128))
Manoel_costa = pygame.transform.scale(Manoel_c, (128, 128))
Manoel_ladoE = pygame.transform.scale(Manoel_le, (128, 128))
Manoel_ladoD = pygame.transform.scale(Manoel_ld, (128, 128))

Caveira_f = pygame.image.load('IMAGENS\Caveira_frente.png')
Caveira_c = pygame.image.load('IMAGENS\Caveira_costa.png')
Caveira_le = pygame.image.load('IMAGENS\Caveira_ladoE.png')
Caveira_ld = pygame.image.load('IMAGENS\Caveira_ladoD.png')
Caveira_frente = pygame.transform.scale(Caveira_f, (96, 96))
Caveira_costa = pygame.transform.scale(Caveira_c, (96, 96))
Caveira_ladoE = pygame.transform.scale(Caveira_le, (96, 96))
Caveira_ladoD = pygame.transform.scale(Caveira_ld, (96, 96))
Som_Caveira = pygame.mixer.Sound('SONS\Som_Caveira.mp3')
Som_Caveira.set_volume(0.07)

Morcego_f = pygame.image.load('IMAGENS\Morcego_frente.png')
Morcego_c = pygame.image.load('IMAGENS\Morcego_costa.png')
Morcego_le = pygame.image.load('IMAGENS\Morcego_ladoE.png')
Morcego_ld = pygame.image.load('IMAGENS\Morcego_ladoD.png')
Morcego_frente = pygame.transform.scale(Morcego_f, (80, 80))
Morcego_costa = pygame.transform.scale(Morcego_c, (80, 80))
Morcego_ladoE = pygame.transform.scale(Morcego_le, (80, 80))
Morcego_ladoD = pygame.transform.scale(Morcego_ld, (80, 80))
Som_Morcego = pygame.mixer.Sound('SONS\Som_Morcego.mp3')
Som_Morcego.set_volume(0.07)


Coracao_v = pygame.image.load('IMAGENS\Coracao_vermelho.png')
Coracao_vermelho = pygame.transform.scale(Coracao_v, (64, 64))
Som_Vida = pygame.mixer.Sound('SONS\Som_Vida.mp3')
Som_Pegar_Vida = pygame.mixer.Sound('SONS\Som_Pegar_Vida.mp3')
Som_Vida.set_volume(0.08)

Bola_a = pygame.image.load('IMAGENS\Bola_arma2.png')
Bola_arma = pygame.transform.scale(Bola_a, (32, 32))
